#' Plot Daily Weather-Seed Relationships
#'
#' This function generates a bar plot visualizing the relationship between daily weather variables and seed production
#' metrics (e.g., slope estimates, correlation, p-values, R²) across reversed time (days before an event) or by
#' calendar day-of-year (DOY). It supports binary coloring for positive/negative effects or uniform color when plotting
#' p-values and R².
#'
#' @param daily.relation.res A data frame with daily results (e.g., from `runing_daily_relationship()`) that includes
#' columns such as `days.reversed`, `correlation`, `estimate`, `p.value`, or `r.squared`.
#' @param calendar A calendar data frame generated by `generate_reverse_day_calendar()` that includes `days.reversed`
#' and `DOY` (day-of-year) for plotting options.
#' @param x_axis Character string specifying which x-axis to use. Either `"reversed.day"` (default) or `"doy"`.
#' @param whattoplot Character string indicating which metric to visualize. Options: `"estimate"`, `"correlation"`
#' (default), `"p.value"`, or `"r.squared"`.
#' @param binary_colors A character vector of two colors to represent positive and negative values. Default:
#' `c("#00AFBB", "#FC4E07")`.
#' @param highlight_window Optional numeric vector of one or two day values (e.g., `c(400, 460)`) to mark with vertical
#' dashed lines and optionally a horizontal bar segment across the specified period.
#' @param yseg Numeric value for the y-position of the horizontal segment used to annotate `highlight_window` (default: 0.2).
#'
#' @return A `ggplot2` object showing the daily relationship between a weather variable and seed production, with
#' bars colored by sign (positive/negative) or uniformly for other metrics.
#'
#' @examples
#' \dontrun{
#' calendar <- generate_reverse_day_calendar(refday = 305, lastdays = 180, yearback = 1)
#' plot_daily_relation(
#'   daily.relation.res = daily_output,
#'   calendar = calendar,
#'   x_axis = "reversed.day",
#'   whattoplot = "correlation",
#'   binary_colors = c("steelblue", "firebrick"),
#'   highlight_window = c(398, 458),
#'   yseg = 0.15
#' )
#' }
#'
#' @import ggplot2
#' @import dplyr
#' @importFrom rlang sym !!
#' @export
plot_daily_relation <- function(
  daily.relation.res,
  calendar,
  x_axis = c("reversed.day", "doy"),
  whattoplot = c("estimate", "correlation", "p.value", "r.squared"),
  binary_colors = c("#00AFBB", "#FC4E07"),
  highlight_window = NULL,
  yseg = 0.2
) {
  x_axis <- match.arg(x_axis)
  whattoplot <- match.arg(whattoplot)

  # Merge with calendar
  df <- daily.relation.res %>%
    dplyr::left_join(calendar, by = c("days.reversed" = "days.reversed"))

  # Choose plotting column
  y_var <- rlang::sym(whattoplot)

  # Format for binary coloring if needed
  df <- df %>%
    dplyr::mutate(
      sign = ifelse(!!y_var > 0, "positive", "negative"),
      bar_color = if (whattoplot %in% c("estimate", "correlation")) sign else
        "onecolor"
    )

  x_mapping <- if (x_axis == "reversed.day") aes(x = days.reversed) else
    aes(x = DOY)
  x_label <- if (x_axis == "reversed.day") "Days reversed" else "Day of year"

  p <- ggplot2::ggplot(df, x_mapping) +
    ggplot2::geom_bar(
      ggplot2::aes(
        y = !!y_var,
        fill = bar_color,
        color = bar_color
      ),
      stat = "identity",
      alpha = 0.3
    ) +
    ggplot2::scale_color_manual(
      values = if (whattoplot %in% c("estimate", "correlation"))
        binary_colors else binary_colors[1]
    ) +
    ggplot2::scale_fill_manual(
      values = if (whattoplot %in% c("estimate", "correlation"))
        binary_colors else binary_colors[1]
    ) +
    ggplot2::theme(legend.position = "none") +
    ggplot2::ylab(whattoplot) +
    ggplot2::xlab(x_label)

  if (!is.null(highlight_window)) {
    for (w in highlight_window) {
      p <- p + ggplot2::geom_vline(xintercept = w, linetype = "dashed")
    }
    if (length(highlight_window) == 2) {
      p <- p +
        ggplot2::annotate(
          "segment",
          x = highlight_window[1],
          xend = highlight_window[2],
          y = yseg,
          yend = yseg,
          linewidth = 1,
          color = "black"
        )
    }
  }

  return(p)
}
